spring:
  application:
    name: cloud-demo-service-c
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 9013

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 # 客户端发送心跳到Eureka频率
    lease-expiration-duration-in-seconds: 2  # 客户端有效期，即2秒没发送心跳，则表示服务挂掉，Eureka剔除本服务
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    registry-fetch-interval-seconds: 2 # 客户端拉取服务注册消息的频率

feign:
  hystrix:
    enabled: true # 开启feign的断路器功能
