ribbon:
  ConnectTimeout: 1000 # 请求连接的超时时间
  ReadTimeout: 10000 # 请求处理的超时时间
  MaxAutoRetries: 1 # 当前实例的重试次数
  MaxAutoRetriesNextServer: 0 # 切换实例的重试次数

logging:
  level:
    root: warn
    com.yclouds: debug